name: Developer Portal
highlighter: pygments
baseurl: /developerportal
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
apikeyurl: 'https://api.govwizely.com'
apikey: '_aZaWWLd8jSl8Ha4S6Xv7OMI'
